### ISSUE TITLE
What is the precise version of pytorch and cuda

### ISSUE THREAD

**Issue by yingli663** [dyh127/Adaptive-Exploration-for-Unsupervised-Person-Re-Identification#1]
I have tried pytorch(1.0.0) and cuda(8.0).
But I received the error:
```
log_dir= checkpoint/AE_duke2market_xi_0.6
Namespace(arch='resnet50', batch_size=128, data_dir='data/', delta=3.5, dropout=0.5, epochs=60, epochs_decay=40, evaluate=False, features=4096, height=256, lambda0=0.55, logs_dir='checkpoint/AE_duke2market_xi_0.6', lr=0.1, momentum=0.9, mu=0.4, output_feature='pool5', print_freq=50, re=0.5, resume='', source='duke', target='market', tau=0.05, weight_decay=0.0005, width=128, workers=8, xi=0.6)
For target train set, indexes are treated as identities of images
Data dataset loaded
  subset   | # ids | # images
  ---------------------------
  source train    |     0 |        0
  target train    |     0 |        0
  query    |     0 |        0
  gallery  |     0 |        0
Traceback (most recent call last):
  File "main.py", line 231, in <module>
    main(args)
  File "main.py", line 101, in main
    args.re, args.workers)
  File "main.py", line 52, in get_data
    shuffle=True, pin_memory=True, drop_last=True)
  File "/home/yl/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 802, in __init__
    sampler = RandomSampler(dataset)
  File "/home/yl/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 64, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integeral value, but got num_samples=0

```
I think it is caused by incorrect version of pytorch and cuda

**Comment by yingli663** [comment]
It is caused by the incorrect location of the `data` folder.
The `data` folder should be under the project folder.
